In [8]:
import numpy as np
import pandas as pd

# 1. Привести различные способы создания объектов типа Series
# Для создания Series можно использовать

# - списки Python или массивы NumPy
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)

print('_______________')

data_array = np.array([10, 20, 30, 40, 50])
s = pd.Series(data_array)
print(s)

print('_______________')

# - скалярные значения
num = 4
s = pd.Series(num, index=[0, 1, 2, 3, 4])
print(s)

print('_______________')

# - словари
data_dict = {"a": 1, "b": 2, "c": 3}
s = pd.Series(data_dict)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64
_______________
0    10
1    20
2    30
3    40
4    50
dtype: int64
_______________
0    4
1    4
2    4
3    4
4    4
dtype: int64
_______________
a    1
b    2
c    3
dtype: int64


In [13]:
# 2. Привести различные способы создания объектов типа DataFrame
# DataFrame. Способы создания:

# - через объекты Series
s1 = pd.Series([1, 2, 3], name="col1")
s2 = pd.Series([4, 5, 6], name="col2")
df = pd.DataFrame({"col1": s1, "col2": s2})
print(df)

# - через списки словарей
data = [{"name": "A", "age": 25}, {"name": "S", "age": 30}]
df = pd.DataFrame(data)
print(df)


# - через словари объектов Series
data_dict = {"name": pd.Series(["A", "B"]), "age": pd.Series([25, 30])}
df = pd.DataFrame(data_dict)
print(df)


# - через двумерный массив NumPy
data_array = np.array([[2002, 12, 10], [2005, 8, 7]])
df = pd.DataFrame(data_array, columns=["year", "month", "day"])
print(df)


# - через структурированный массив NumPy
data_structured = np.array([(1, "A"), (2, "B")], dtype=[("id", int), ("name", "U10")])
df = pd.DataFrame(data_structured)
print(df)


   col1  col2
0     1     4
1     2     5
2     3     6
  name  age
0    A   25
1    S   30
  name  age
0    A   25
1    B   30
   year  month  day
0  2002     12   10
1  2005      8    7
   id name
0   1    A
1   2    B


In [16]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы вместо NaN было установлено значение 1
s1 = pd.Series([1, 2, 3], index=["a", "b", "c"])
s2 = pd.Series([4, 5], index=["c", "d"])

print(s1)
print(s2)
print(s1 + s2)

# Объединение Series с заполнением отсутствующих значений значением 1
res = (s1 + s2).fillna(1)

print(res)

a    1
b    2
c    3
dtype: int64
c    4
d    5
dtype: int64
a    NaN
b    NaN
c    7.0
d    NaN
dtype: float64
a    1.0
b    1.0
c    7.0
d    1.0
dtype: float64


In [33]:
# 4. Переписать пример с транслированием для DataFrame так, чтоюы вычитание происходило по столбцам

rng = np.random.default_rng()

A = rng.integers(0, 10, (3, 4))
print(A)

df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)

print(df.T.iloc[0])

print((df.T - df.T.iloc[0]).T)

print(df.T.iloc[0, ::2])

print((df.T - df.T.iloc[0, ::2]).T)

[[1 2 4 5]
 [7 2 7 0]
 [1 7 4 4]]
   a  b  c  d
0  1  2  4  5
1  7  2  7  0
2  1  7  4  4
0    1
1    7
2    1
Name: a, dtype: int64
   a  b  c  d
0  0  1  3  4
1  0 -5  0 -7
2  0  6  3  3
0    1
2    1
Name: a, dtype: int64
     a    b    c    d
0  0.0  1.0  3.0  4.0
1  NaN  NaN  NaN  NaN
2  0.0  6.0  3.0  3.0


In [34]:
# 5. На примере объектов DataFrame продемонстрируйте методов ffill() и bfill()
rng = np.random.default_rng()
data = {'A': [1, 2, np.nan, 4, 5],
        'B': [np.nan, 2, 3, np.nan, 5],
        'C': [1, 2, 3, 4, 5]}
df = pd.DataFrame(data)
print(df)

# Заполнение пропущенных значений методом ffill() -- заполняет пропущенные значения, двигаясь вперед по данным
print(df.ffill())

# Заполнение пропущенных значений методом bfill() -- заполняет пропущенные значения, двигаясь назад по данным
print(df.bfill())

     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  NaN  3.0  3
3  4.0  NaN  4
4  5.0  5.0  5
     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  2.0  3.0  3
3  4.0  3.0  4
4  5.0  5.0  5
     A    B  C
0  1.0  2.0  1
1  2.0  2.0  2
2  4.0  3.0  3
3  4.0  5.0  4
4  5.0  5.0  5
