In [1]:
import numpy as np
import pandas as pd

index = [
    ('city_1', 2010, 1),
    ('city_1', 2010, 2),
    ('city_1', 2020, 1),
    ('city_1', 2020, 2),
    ('city_2', 2010, 1),
    ('city_2', 2010, 2),
    ('city_2', 2020, 1),
    ('city_2', 2020, 2),
    ('city_3', 2010, 1),
    ('city_3', 2010, 2),
    ('city_3', 2020, 1),
    ('city_3', 2020, 2),
]

population = [
    101,
    1010,
    201,
    2010,
    102,
    1020,
    202,
    2020,
    103,
    1030,
    203,
    2030,
]

multi_index = pd.MultiIndex.from_tuples(index)

pop = pd.Series(population, index=multi_index)

pop_df = pd.DataFrame(
    {
        'total': pop,
        'something': [
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
        ]
    }
)

print(pop_df)
print('_____________________')

pop_df_city_1 = pop_df.loc['city_1', 'something']
print(pop_df_city_1)
print('_____________________')

pop_df_city_1 = pop_df.loc[['city_1', 'city_3'], ['total', 'something']]
print(pop_df_city_1)
print('_____________________')

pop_df_city_1 = pop_df.loc[['city_1', 'city_3'], 'something']
print(pop_df_city_1)

               total  something
city_1 2010 1    101         10
            2   1010         11
       2020 1    201         12
            2   2010         13
city_2 2010 1    102         14
            2   1020         15
       2020 1    202         16
            2   2020         17
city_3 2010 1    103         18
            2   1030         19
       2020 1    203         20
            2   2030         21
_____________________
2010  1    10
      2    11
2020  1    12
      2    13
Name: something, dtype: int64
_____________________
               total  something
city_1 2010 1    101         10
            2   1010         11
       2020 1    201         12
            2   2010         13
city_3 2010 1    103         18
            2   1030         19
       2020 1    203         20
            2   2030         21
_____________________
city_1  2010  1    10
              2    11
        2020  1    12
              2    13
city_3  2010  1    18
              2    19
        2020

In [39]:
# 2. Из получившихся данных выбрать данные по

index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names = ['city', 'year']
)

print(index)

columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names = ['worker', 'job']
)

rng = np.random.default_rng(1)

data = rng.random((4, 6))
print(data)

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)
print('_______________________________________')

# - 2020 году (для всех столбцов)

data_2020 = data_df.loc[:, 2020, :]
print(data_2020)
print('_______________________________________')

# - job_1 (для всех строк)

data_job_1 = data_df.loc[:, (slice(None), 'job_1')]
print(data_job_1)
print('_______________________________________')

# - для city_1 и job_2

data_city_1_job_2 = data_df.loc[('city_1',), (slice(None), 'job_2',)]
print(data_city_1_job_2)

MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           names=['city', 'year'])
[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
_______________________________________
worker  person_1       

In [71]:
# 3. Взять за основу DataFrame со следующей структурой:

index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names = ['city', 'year']
)

print(index)
print('_____________________')

columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names = ['worker', 'job']
)

rng = np.random.default_rng(1)
data = rng.random((4, 6))

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)
print('______________________')


# Выполнить запрос на получение следующих данных:
# - все данные по person_1 и person_3
print(data_df.loc[:, pd.IndexSlice[['person_1', 'person_3'], :]])
print('___________________________')

# - все данные по city_1 и первым двум person-ам (с использовнием срезов)
print(data_df.loc[pd.IndexSlice['city_1', :], pd.IndexSlice[['person_1', 'person_2'], :]])
print('_________________________')

# приведите пример с импользованием pd.IndexSlice

index = pd.MultiIndex.from_product(
    [
        ['msc', 'spb'],
         ['1900', '2000']
    ],
    names=['name', 'year']
)
columns = ['col1', 'col2']
df = pd.DataFrame([[1000, 2000], [30000, 40000], [5000, 6000], [70000, 80000]], index=index, columns=columns)

print(df)
print('_______________________')

# Используем IndexSlice для выбора данных
idx = pd.IndexSlice
s = df.loc[idx['msc', :], :]  # Выбираем все строки, где 'name' равно 'msc'

print(s)
print('______________________')

s2 = df.loc[idx[:, '1900'], 'col2'] # выбираем все строки, где year='1900', и только столбец 'col2'

print(s2)


MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           names=['city', 'year'])
_____________________
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
______________________
worker       person_1            person_3          
job             job_1     job_2     job_1     job_2
city   year                                        
city_1 2010  0.511822  0.950464  0.311831  0.423326
       2020  0.827703  0.409199  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.

In [79]:
# 4. Привести пример использования inner и outer джойнов для Series

ser1 = pd.Series(['a', 'b', 'c'], index = [1, 2, 3])
ser2 = pd.Series(['b', 'c', 'f'], index = [2, 3, 4])

# axis = 0 по умолчанию
print(pd.concat([ser1, ser2], axis = 1, join = 'outer')) # -- объединяет по столбцам, сохраняет индексы из обоих Series, если индекс отсутствует в одном из Series, то добавляется NaN
print('____________________')
print(pd.concat([ser1, ser2], axis = 1, join = 'inner')) # -- объединяет по столбцам, сохраняет только общие индексы

     0    1
1    a  NaN
2    b    b
3    c    c
4  NaN    f
____________________
   0  1
2  b  b
3  c  c
