In [40]:
import numpy as np
import sys
import array

## 1. Какие ещё существуют коды типов?
a1 = array.array('i', [1, 2, 3]) # -- целые числа, которые могут быть как положительными, так и отрицательными
print(sys.getsizeof(a1))

a2 = array.array('b', [122, 24]) # -- целые числа без знака от 0 до 255
print(sys.getsizeof(a2))

a3 = array.array('B', [True, False]) # -- Булевы (логические значения True или False)
print(sys.getsizeof(a3))

a4 = array.array('u', ['5', 'L']) # -- символы Unicode
print(sys.getsizeof(a4))

a5 = array.array('f', [-7.676, 0.1]) # -- числа с плавающей точкой (плавающие точки одинарной точности)
print(sys.getsizeof(a5))

a6 = array.array('d', [0.6263546725467253745723, 9.8726365735545537632]) # -- числа с двойной точностью (плавающие точки двойной точности)
print(a6)
print(sys.getsizeof(a6))

a7 = array.array('l', [-8326498264286754, 28367482638]) # -- длинные целые числа от -(2^31) до (2^31 - 1)
print(sys.getsizeof(a7))

a8 = array.array('L', [3926928639823, 2937825834872093]) # -- длинные целые числа без знака от 0 до (2^32 - 1)
print(sys.getsizeof(a8))

a9 = array.array('q', [-234567890987, 45678876545678]) # -- длинные целые числа от -(2^63) до (2^63 - 1)
print(sys.getsizeof(a9))

a10 = array.array('Q', [0, 7123571537512712537]) # -- длинные целые числа без знака от 0 до (2^63 - 1)
print(sys.getsizeof(a10))

92
82
82
88
88
array('d', [0.6263546725467254, 9.872636573554553])
96
96
96
96
96


In [41]:
## 2. Напишите код, подобный приведённому выше, но с дргуим типом

a3 = array.array('B', [True, False])
print(sys.getsizeof(a3))
print(type(a3))

82
<class 'array.array'>


In [43]:
## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [46]:
## 4. Напишите код для создания массива с 5 равномерно распределёнными случайными значениями в диапазоне от 0 до 1
a = np.random.uniform(0, 1, 5)
print(a)

[0.7527076  0.70359085 0.71212441 0.43901163 0.93058303]


In [47]:
## 5. Напишите код для создания массива с 5 нормально распределёнными случайными значениями с мат. ожиданием = 0 и дисперсией 1
a = np.random.normal(0, 1, 5)
print(a)

[-0.85608266 -1.45426374 -1.75302501  0.93974019 -1.24775689]


In [48]:
## 6. Напишите код для создания массива с 5 случайными целыми числами в диапазоне [0, 10)
a = np.random.randint(0, 10, 5)
print(a)

[1 2 5 6 0]


In [57]:
## 7. Написать код для создания срезов массива 3 на 4
a = np.random.randint(0, 10, (3, 4))
print(a)
print('_______________')

# - первые две строки и три столбца
print(a[:2, :3])
print('_______________')

# - первые три строки и второй столбец
print(a[:3, 1:2])
print('_______________')

# - все строки и столбцы в обратном порядке
print(a[::-1, ::-1])
print('_______________')

# - второй столбец
print(a[:, 1])
print('_______________')

# - третья строка
print(a[2, :])

[[7 8 3 5]
 [4 0 2 9]
 [6 9 6 2]]
_______________
[[7 8 3]
 [4 0 2]]
_______________
[[8]
 [0]
 [9]]
_______________
[[2 6 9 6]
 [9 2 0 4]
 [5 3 8 7]]
_______________
[8 0 9]
_______________
[6 9 6 2]


In [58]:
# 8. Продемонстрируйте, как сделать срез-копию

a = np.array([1, 2, 3, 4, 5, 6])

b = a[:3].copy()
print(b)

b[0] = 100
print(a)

[1 2 3]
[1 2 3 4 5 6]


In [59]:
# 9. Продемонстрировать использование newaxis для получения вектора-столбца и вектора-строки

arr = np.array([1, 2, 3])

# Получение вектора-столбца
col_vect = arr[:, np.newaxis]
print(col_vect)

# Получение вектора-строки
row_vect = arr[np.newaxis, :]
print(row_vect)

[[1]
 [2]
 [3]]
[[1 2 3]]


In [63]:
# 10. Разберитесь, как работает метод dstack

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

# Стекование массивов вдоль третьей оси
a = np.dstack((a1, a2))
print(a)

# Входные массивы: dstack() принимает последовательность массивов, которые должны иметь одинаковое количество измерений и одинаковый размер вдоль всех осей, кроме последней. Например, если у вас есть два двумерных массива, они должны иметь одинаковое количество строк, но могут иметь разное количество столбцов.
# Стекование: метод dstack() объединяет массивы вдоль третьей оси (глубинной оси). Каждый массив в последовательности становится новым срезом вдоль третьей оси в результирующем массиве. Если исходные массивы двумерные, то результирующий массив будет трехмерным.
# Форма результирующего массива: форма результирующего массива будет равна форме входных массивов, но с добавлением новой оси в конце. Например, если у вас есть два двумерных массива с формой (2, 3), то результирующий массив после dstack() будет иметь форму (2, 3, 2).

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [79]:
# 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit

a = np.arange(16).reshape(4, 4)
print(a)
print('______________')

# Разделение массива на 4 подмассива вдоль оси 0 и оси 1, соответственно
a1 = np.split(a, 4, axis=0)
print(a1)
print('______________')

a2 = np.split(a, 4, axis=1)
print(a2)
print('______________')

# Разделение массива на 2 подмассива вдоль оси 0 с помощью vsplit
a3 = np.vsplit(a, 2)
print(a3)
print('______________')

# Разделение массива на 2 подмассива вдоль оси 1 с помощью hsplit
a4 = np.hsplit(a, 2)
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
______________
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
______________
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
______________
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
______________
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [87]:
# 12. Привести примеры использования всех универсальных функций, приведённых на занятии
# - - / // ** %

x = np.arange(10)
print(x)

print(-x) # -- взятие отрицания
print(x - 100) # -- вычитание
print(x/5) # -- деление
print(x//2) # -- целочисленное деление
print(x**5) # -- возведение в степень
print(x%5) # -- остаток от деления

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[0 0 1 1 2 2 3 3 4 4]
[    0     1    32   243  1024  3125  7776 16807 32768 59049]
[0 1 2 3 4 0 1 2 3 4]
