In [8]:
import numpy as np
import sys
import array

# Типы данных Python

x = 1
print(type(x))
print(sys.getsizeof(x))

x = 'hello'
print(type(x))
print(sys.getsizeof(x))

x = True
print(type(x))
print(sys.getsizeof(x))

l1 = list([])
print(sys.getsizeof(l1))

l2 = list([1, 2, 3])
print(sys.getsizeof(l2))

l3 = list([1, '2', True])
print(l3)

a1 = array.array('i', [1, 2, 3])
print(sys.getsizeof(a1))
print(type(a1))

<class 'int'>
28
<class 'str'>
54
<class 'bool'>
28
56
88
[1, '2', True]
92
<class 'array.array'>


In [14]:
a = np.array([1, 2, 3, 4, 5])
print(type(a), a)

# "повышающее" приведение типов
a  = np.array([1.23, 2, 3, 4, 5])
print(type(a), a)

a  = np.array([1.23, 2, 3, 4, 5], dtype = int)
print(type(a), a)

a = np.array([range(i, i+3) for i in [2, 4, 6]])
print(a, type(a))

<class 'numpy.ndarray'> [1 2 3 4 5]
<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]
<class 'numpy.ndarray'> [1 2 3 4 5]
[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'>


In [21]:
a = np.zeros(10, dtype=int)
print(a, type(a))

a = np.ones((3, 5), dtype=float)
print(a, type(a))

print(np.full((4, 5), 3.1415))

print(np.arange(0, 20, 2))

print(np.eye(4))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>
[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]
[ 0  2  4  6  8 10 12 14 16 18]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
### МАССИВЫ

np.random.seed(1)

x1 = np.random.randint(10, size = 3)
x2 = np.random.randint(10, size = (3, 2))
x3 = np.random.randint(10, size = (3, 2, 2))

print(x1)
print(x2)
print(x3)

print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

# ndim -- число размерностей
# shape -- размер каждой размерности
# size -- общий размер массива

[5 8 9]
[[5 0]
 [0 1]
 [7 6]]
[[[9 2]
  [4 5]]

 [[2 4]
  [2 4]]

 [[7 7]
  [9 1]]]
1 (3,) 3
2 (3, 2) 6
3 (3, 2, 2) 12


In [39]:
# Индекес (с 0)
a = np.array([1, 2, 3, 4, 5])
print(a[0])

print(a[-2])

a[1] = 20

print(a)

a = np.array([[1, 2], [3, 4]])
print(a)

print(a[0, 0])
print(a[-1, -1])

a[1, 0] = 100
print(a)

1
4
[ 1 20  3  4  5]
[[1 2]
 [3 4]]
1
4
[[  1   2]
 [100   4]]


In [41]:
a = np.array([1, 2, 3, 4])
b = np.array([1.0, 2, 3, 4])

print(a)
print(b)

a[0] = 10
print(a)

a[0] = 10.123
print(a)

[1 2 3 4]
[1. 2. 3. 4.]
[10  2  3  4]
[10  2  3  4]


In [53]:
## Срез [s:f:step] [1:shape:1] -- это не копия, а ссылка

a = np.array([1, 2, 3, 4, 5, 6])

print(a[0:3:1])
print(a[:3:1])
print(a[:3])
print('___________')

print(a[3:])
print('___________')

print(a[1:5])
print(a[1:-1])
print('___________')

print(a[1:6:2])
print(a[1::2])
print('___________')

print(a[::1])
print(a[::-1])

[1 2 3]
[1 2 3]
[1 2 3]
___________
[4 5 6]
___________
[2 3 4 5]
[2 3 4 5]
___________
[2 4 6]
[2 4 6]
___________
[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [55]:
a = np.array([1, 2, 3, 4, 5, 6])

b = a[:3]
print(b)

b[0] = 100
print(a)

[1 2 3]
[100   2   3   4   5   6]


In [58]:
a = np.arange(1, 13)

print(a)

print(a.reshape(2, 6))
print(a.reshape(3, 4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])

print(np.concatenate([x, y, z]))
print('__________')

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

r1 = np.vstack([x, y])
print(r1)
print('__________')

print(np.hstack([r1, r1]))

[1 2 3 4 5 6]
__________
[[1 2 3]
 [4 5 6]]
__________
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [68]:
### ВЫЧИСЛЕНИЯ С МАССИВАМИ

# Векторизированные операции -- независимо к каждому элементу массива

x = np.arange(10)
print(x)

print(x*2 + 1)

# Универсальные функции

print(np.multiply(x, 2))
print(np.add(np.multiply(x, 2), 1))

# - - / // ** %
## np.abs, sin/cos/tan/..., exp, log

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]


In [72]:
x = np.arange(5)

y = np.empty(5)
print(np.multiply(x, 10, out=y))

print(y)

x = np.arange(5)

y = np.empty(10)
print(np.multiply(x, 10, out=y[::2]))

print(y)

x = np.arange(5)

y = np.zeros(10)
print(np.multiply(x, 10, out=y[::2]))

print(y)

[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]
[0.0e+000 4.9e-324 1.0e+001 1.5e-323 2.0e+001 2.5e-323 3.0e+001 3.5e-323
 4.0e+001 4.4e-323]
[ 0. 10. 20. 30. 40.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [77]:
x = np.arange(1, 5)

print(x)

print(np.add.reduce(x))
print(np.add.accumulate(x))

[1 2 3 4]
10
[ 1  3  6 10]


In [79]:
x = np.arange(1, 10)
print(np.add.outer(x, x))
print('______________')
print(np.multiply.outer(x, x))

[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
______________
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
