In [1]:
import pandas as pd
import numpy as np

# Если размерность данных > 2, то используют иерархическую индексацию(мультииндекс). В один индекс включается несколько уровней.

index = [
    ('city_1', 2010),
    ('city_1', 2020),
    ('city_2', 2010),
    ('city_2', 2020),
    ('city_3', 2010),
    ('city_3', 2020),
]

population = [
    101,
    201,
    102,
    202,
    103,
    203,
]

pop = pd.Series(population, index = index)

print(pop)

print(pop[[i for i in pop.index if i[1] == 2020]])

# Multiindex

index = pd.MultiIndex.from_tuples(index)

pop = pop.reindex(index)

print(pop)

print(pop[:, 2020])

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    102
(city_2, 2020)    202
(city_3, 2010)    103
(city_3, 2020)    203
dtype: int64
(city_1, 2020)    201
(city_2, 2020)    202
(city_3, 2020)    203
dtype: int64
city_1  2010    101
        2020    201
city_2  2010    102
        2020    202
city_3  2010    103
        2020    203
dtype: int64
city_1    201
city_2    202
city_3    203
dtype: int64


In [9]:
pop_df = pop.unstack()
print(pop_df)

print(pop_df.stack())

        2010  2020
city_1   101   201
city_2   102   202
city_3   103   203
city_1  2010    101
        2020    201
city_2  2010    102
        2020    202
city_3  2010    103
        2020    203
dtype: int64


In [20]:
index = [
    ('city_1', 2010, 1),
    ('city_1', 2010, 2),

    ('city_1', 2020, 1),
    ('city_1', 2020, 2),

    ('city_2', 2010, 1),
    ('city_2', 2010, 2),

    ('city_2', 2020, 1),
    ('city_2', 2020, 2),

    ('city_3', 2010, 1),
    ('city_3', 2010, 2),

    ('city_3', 2020, 1),
    ('city_3', 2020, 2),

]

population = [
    101,
    1010,
    201,
    2010,
    102,
    1020,
    202,
    2020,
    103,
    1030,
    203,
    2030,
]

pop = pd.Series(population, index = index)

print(pop)

index = pd.MultiIndex.from_tuples(index)

pop = pop.reindex(index)
print(pop)

print(pop[:, 2010])
print(pop[:, :, 2])

pop_df = pop.unstack()

print(pop_df)
print(pop_df.stack())

(city_1, 2010, 1)     101
(city_1, 2010, 2)    1010
(city_1, 2020, 1)     201
(city_1, 2020, 2)    2010
(city_2, 2010, 1)     102
(city_2, 2010, 2)    1020
(city_2, 2020, 1)     202
(city_2, 2020, 2)    2020
(city_3, 2010, 1)     103
(city_3, 2010, 2)    1030
(city_3, 2020, 1)     203
(city_3, 2020, 2)    2030
dtype: int64
city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     102
              2    1020
        2020  1     202
              2    2020
city_3  2010  1     103
              2    1030
        2020  1     203
              2    2030
dtype: int64
city_1  1     101
        2    1010
city_2  1     102
        2    1020
city_3  1     103
        2    1030
dtype: int64
city_1  2010    1010
        2020    2010
city_2  2010    1020
        2020    2020
city_3  2010    1030
        2020    2030
dtype: int64
               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  102  1020
       2020  202  2020

In [ ]:
index = [
    ('city_1', 2010, 1),
    ('city_1', 2010, 2),

    ('city_1', 2020, 1),
    ('city_1', 2020, 2),

    ('city_2', 2010, 1),
    ('city_2', 2010, 2),

    ('city_2', 2020, 1),
    ('city_2', 2020, 2),

    ('city_3', 2010, 1),
    ('city_3', 2010, 2),

    ('city_3', 2020, 1),
    ('city_3', 2020, 2),

]

population = [
    101,
    1010,
    201,
    2010,
    102,
    1020,
    202,
    2020,
    103,
    1030,
    203,
    2030,
]

pop = pd.Series(population, index = index)

print(pop)

index = pd.MultiIndex.from_tuples(index)

pop_df = pd.DataFrame(
    {
        'total': pop,
        'something': [
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
        ]
    }
)

print(pop_df)

print(pop_df['something'])


In [32]:
### Как можно создать мультииндексы:
## - список массивов, задающих значение индекса на каждом уровнне

il = pd.MultiIndex.from_arrays(
    [
        ['a', 'a', 'b', 'b'],
        [1, 2, 1, 2]
    ]
)

print(il)

## - список кортежей, задающих значение индекса в каждой точке
i2 = pd.MultiIndex.from_tuples(
    [
        ('a', 1),
        ('a', 2),
        ('b', 1),
        ('b', 2),
    ]
)

print(i2)

## - декартово произведение обычных индексов

i3 = pd.MultiIndex.from_product(
    [
        ['a', 'b'],
        [1, 2]
    ]
)

print(i3)

## - описание внутреннего представления: levels, codes

i4 = pd.MultiIndex(
    levels = [
        ['a', 'b', 'c'],
        [1, 2]
    ],
    codes = [
        [0, 0, 1, 1, 2, 2],
        [0, 1, 0, 1, 0, 1],
    ]
)

print(i4)

# - Уровням можно задавать названия

data = {
    ('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001,
}

s = pd.Series(data)
print(s)

s.index.names = ['city', 'year']
print(s)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64
city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [2]:
index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names = ['city', 'year']
)

print(index)

columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names = ['worker', 'job']
)

rng = np.random.default_rng(1)

data = rng.random((4, 6))
print(data)

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)

MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           names=['city', 'year'])
[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737


In [10]:
# Индексация и срезы по мультииндексу

data = {
    ('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001,
    ('city_3', 2010): 10001,
    ('city_3', 2020): 20001,
}

s = pd.Series(data)
s.index.names = ['city', 'year']

print(s['city_1', 2010])
print('_______________________')

print(s['city_1'])
print('___________________')

print(s.loc['city_1':'city_2'])
print('_______________________')

print(s[s>2000])
print('____________________')

print(s[['city_1', 'city_2']])

100
_______________________
year
2010    100
2020    200
dtype: int64
___________________
city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64
_______________________
city    year
city_2  2020     2001
city_3  2010    10001
        2020    20001
dtype: int64
____________________
city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [12]:
# Перегруппировка мультииндексов

index = pd.MultiIndex.from_product(
    [
        ['a', 'c', 'b'],
        [1, 2]
    ]
)

rng = np.random.default_rng(1)

data = pd.Series(rng.random(6), index = index)
data.index.names = ['char', 'int']

print(data)

data = data.sort_index()

print(data['a':'b']) # - машина ожидает, что индексы будут отсортированы

char  int
a     1      0.511822
      2      0.950464
c     1      0.144160
      2      0.948649
b     1      0.311831
      2      0.423326
dtype: float64
char  int
a     1      0.511822
      2      0.950464
b     1      0.311831
      2      0.423326
dtype: float64


In [19]:
index = [
    ('city_1', 2010, 1),
    ('city_1', 2010, 2),

    ('city_1', 2020, 1),
    ('city_1', 2020, 2),

    ('city_2', 2010, 1),
    ('city_2', 2010, 2),

    ('city_2', 2020, 1),
    ('city_2', 2020, 2),

    ('city_3', 2010, 1),
    ('city_3', 2010, 2),

    ('city_3', 2020, 1),
    ('city_3', 2020, 2),

]

population = [
    101,
    1010,
    201,
    2010,
    102,
    1020,
    202,
    2020,
    103,
    1030,
    203,
    2030,
]

pop = pd.Series(population, index = index)

print(pop)

i = pd.MultiIndex.from_tuples(index)

pop = pop.reindex(i)

print(pop)

print(pop.unstack())
print(pop.unstack(level = 0)) # нулевой устанавливаем столбцами, остальные -- индексы
print(pop.unstack(level = 1)) # первый устанавливаем столбцами, остальные -- индексы
print(pop.unstack(level = 2))

(city_1, 2010, 1)     101
(city_1, 2010, 2)    1010
(city_1, 2020, 1)     201
(city_1, 2020, 2)    2010
(city_2, 2010, 1)     102
(city_2, 2010, 2)    1020
(city_2, 2020, 1)     202
(city_2, 2020, 2)    2020
(city_3, 2010, 1)     103
(city_3, 2010, 2)    1030
(city_3, 2020, 1)     203
(city_3, 2020, 2)    2030
dtype: int64
city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     102
              2    1020
        2020  1     202
              2    2020
city_3  2010  1     103
              2    1030
        2020  1     203
              2    2030
dtype: int64
               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  102  1020
       2020  202  2020
city_3 2010  103  1030
       2020  203  2030
        city_1  city_2  city_3
2010 1     101     102     103
     2    1010    1020    1030
2020 1     201     202     203
     2    2010    2020    2030
          2010  2020
city_1 1   101   201
       2  1010  

In [29]:
# NumPy Конкатенация

x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

print(np.concatenate([x, y, z]))

x = [[1, 2, 3]]
y = [[4, 5, 6]]
z = [[7, 8, 9]]

print(np.concatenate([x, y, z]))
print(np.concatenate([x, y, z], axis = 0))
print(np.concatenate([x, y, z], axis = 1))

# Pandas -- concat

ser1 = pd.Series(['a', 'b', 'c'], index = [1, 2, 3])
ser2 = pd.Series(['d', 'e', 'f'], index = [4, 5, 6])


print(pd.concat([ser1, ser2]))

ser1 = pd.Series(['a', 'b', 'c'], index = [1, 2, 3])
ser2 = pd.Series(['d', 'e', 'f'], index = [1, 2, 6])


print(pd.concat([ser1, ser2]))

ser1 = pd.Series(['a', 'b', 'c'], index = [1, 2, 3])
ser2 = pd.Series(['d', 'e', 'f'], index = [4, 5, 6])


print(pd.concat([ser1, ser2], verify_integrity = False))
print(pd.concat([ser1, ser2], ignore_index = True))
print(pd.concat([ser1, ser2], keys = ['x', 'y']))

ser1 = pd.Series(['a', 'b', 'c'], index = [1, 2, 3])
ser2 = pd.Series(['b', 'c', 'f'], index = [4, 5, 6])

print(pd.concat([ser1, ser2], join = 'outer'))
print(pd.concat([ser1, ser2], join = 'inner'))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
1    a
2    b
3    c
1    d
2    e
6    f
dtype: object
1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
0    a
1    b
2    c
3    d
4    e
5    f
dtype: object
x  1    a
   2    b
   3    c
y  4    d
   5    e
   6    f
dtype: object
1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
