In [2]:
import numpy as np
import pandas as pd

# Pandas -- расширение NumPy (структурированные массивы). Строки и столбцы индексируются метками,  не только числовыми значениями

# Series, DataFrame, Index -- три основным структуры

## Series

data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data))

print(data.values)
print(type(data.values))

print(data.index)
print(type(data.index))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>
[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>


In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data[0])
print([data[1:3]])

0.25
[1    0.50
2    0.75
dtype: float64]


In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print(data)
print(data['a'])
print(data['b':'d'])

print(type(data.index))

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'pandas.core.indexes.base.Index'>


In [13]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [1, 10, 7, 'd'])
print(data)
print(data[10:'d'])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
10    0.50
7     0.75
d     1.00
dtype: float64


In [17]:
population_dict = {
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}

population = pd.Series(population_dict)
print(population)

print(population['city_4'])
print(population['city_4':'city_5'])

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64
1004
city_4    1004
city_5    1005
dtype: int64


In [ ]:
# Для создания Series можно использовать:
# - списки Python или массивы NumPy
# - скалярные значения
# - словари
# 1. Привести различные способы создания объектов типа Series

In [43]:
## DaraFrame -- двумерный массив с явно определёнными индексами. Последовательность "согласованных" объектов Series

population_dict = {
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}

area_dict = {
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

print(population)
print(area)

states = pd.DataFrame({
    'population1': population,
    'area1' : area,
})

print(states)

print(states.values)
print(states.index)
print(states.columns)

print(type(states.values))
print(type(states.index))
print(type(states.columns))

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
dtype: int64
        population1  area1
city_1         1001   9991
city_2         1002   9992
city_3         1003   9993
city_4         1004   9994
city_5         1005   9995
[[1001 9991]
 [1002 9992]
 [1003 9993]
 [1004 9994]
 [1005 9995]]
Index(['city_1', 'city_2', 'city_3', 'city_4', 'city_5'], dtype='object')
Index(['population1', 'area1'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>


In [44]:
print(states['area1'])

# DataFrame. Способы создания
# - через объекты Series
# - через списки словарей
# - через словари объектов Series
# - через двумерный массив NumPy
# - через структурированный массив NumPy
# 2. Привести различные способы создания объектов типа DataFrame

city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64


In [26]:
# Index -- способ организации ссылки на данные объектов Series и DataFrame. Index -- неизменяем, упорядочен, является мультимножеством(в нём могут быть одинаковые элементы)

ind = pd.Index([2, 3, 5, 7, 11])
print(ind[1])
print(ind[::2])

# ind[1] = 5

3
Index([2, 5, 11], dtype='int64')


In [27]:
# Index -- следует соглашениям объекта set (Python)

indA = pd.Index([1, 2, 3, 4, 5])
indB = pd.Index([2, 3, 4, 5, 6])

print(indA.intersection(indB))

Index([2, 3, 4, 5], dtype='int64')


In [34]:
# Выборка данных из Series
## как словарь

data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])

print('a' in data)
print('z' in data)

print(data.keys())

print(list(data.items()))

data['a'] = 100
data['z'] = 1000

print(data)

True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a     100.00
b       0.50
c       0.75
d       1.00
z    1000.00
dtype: float64


In [39]:
## как одномерный массив
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])

print(data['a':'c'])
print(data[0:2])
print(data[(data > 0.5) & (data < 1)])
print(data[['a', 'd']])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
c    0.75
dtype: float64
a    0.25
d    1.00
dtype: float64


In [41]:
# атрибуты-индексаторы
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [1, 3, 10, 15])

print(data[1])

print(data.loc[1])
print(data.iloc[1])

0.25
0.25
0.5


In [47]:
# Выборка данных из DataFrame
## как словарь

population_dict = {
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}

area_dict = {
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
}

pop = pd.Series(
    {
        'city_1': 1001,
        'city_2': 1002,
        'city_3': 1003,
        'city_4': 1004,
        'city_5': 1005,
    })


area = pd.Series(
    {
        'city_1': 9991,
        'city_2': 9992,
        'city_3': 9993,
        'city_4': 9994,
        'city_5': 9995,
    })
data = pd.DataFrame({'area1':area, 'pop1':pop, 'pop':pop})

print(data)

print(data['area1'])
print(data.area1)

print(data.pop1 is data['pop1'])
print(data.pop is data['pop'])

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
True
False


In [49]:
data['new'] = data['area1']

data['new1'] = data['area1'] / data['pop1']

print(data)

        area1  pop1   pop   new      new1
city_1   9991  1001  1001  9991  9.981019
city_2   9992  1002  1002  9992  9.972056
city_3   9993  1003  1003  9993  9.963111
city_4   9994  1004  1004  9994  9.954183
city_5   9995  1005  1005  9995  9.945274


In [57]:
# двумерный NumPy-массив

data = pd.DataFrame({'area1':area, 'pop1':pop})

print(data)

print(data.values)

print(data.T)

print(data['area1']) # образаемся к столбцу

print(data.values[0]) # обращаемся к строке

print(data.values[0:3])

        area1  pop1
city_1   9991  1001
city_2   9992  1002
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005
[[9991 1001]
 [9992 1002]
 [9993 1003]
 [9994 1004]
 [9995 1005]]
       city_1  city_2  city_3  city_4  city_5
area1    9991    9992    9993    9994    9995
pop1     1001    1002    1003    1004    1005
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
[9991 1001]
[[9991 1001]
 [9992 1002]
 [9993 1003]]


In [62]:
# атрибуты-индексаторы

data = pd.DataFrame({'area1':area, 'pop1':pop, 'pop':pop})

print(data)
print(data.iloc[:3, 1:2])
print(data.loc[:'city_3', 'pop1':'pop'])
print(data.loc[data['pop'] > 1002, ['area1', 'pop']])

data.iloc[0, 2] = 999999

print(data)

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
        pop1
city_1  1001
city_2  1002
city_3  1003
        pop1   pop
city_1  1001  1001
city_2  1002  1002
city_3  1003  1003
        area1   pop
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005
        area1  pop1     pop
city_1   9991  1001  999999
city_2   9992  1002    1002
city_3   9993  1003    1003
city_4   9994  1004    1004
city_5   9995  1005    1005


In [6]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0, 10, 4))

print(s)
print(np.exp(s))

0    8
1    9
2    3
3    6
dtype: int64
0    2980.957987
1    8103.083928
2      20.085537
3     403.428793
dtype: float64


In [7]:
pop = pd.Series(
    {
        'city_1': 1001,
        'city_2': 1002,
        'city_3': 1003,
        'city_41': 1004,
        'city_51': 1005,
    })


area = pd.Series(
    {
        'city_1': 9991,
        'city_2': 9992,
        'city_3': 9993,
        'city_42': 9994,
        'city_52': 9995,
    })

data = pd.DataFrame({'area1':area, 'pop1':pop})

print(data)

# NaN -- Not a Number

          area1    pop1
city_1   9991.0  1001.0
city_2   9992.0  1002.0
city_3   9993.0  1003.0
city_41     NaN  1004.0
city_42  9994.0     NaN
city_51     NaN  1005.0
city_52  9995.0     NaN


In [9]:
dfA = pd.DataFrame(rng.integers(0, 10, (2, 2)), columns = ['a', 'b'])
dfB = pd.DataFrame(rng.integers(0, 10, (3, 3)), columns = ['a', 'b', 'c'])

print(dfA)
print(dfB)

print(dfA + dfB)

   a  b
0  3  8
1  3  8
   a  b  c
0  4  2  7
1  6  0  4
2  9  0  1
     a     b   c
0  7.0  10.0 NaN
1  9.0   8.0 NaN
2  NaN   NaN NaN


In [12]:
rng = np.random.default_rng()

A = rng.integers(0, 10, (3, 4))
print(A)

print(A[0])

print(A - A[0])

[[0 8 6 9]
 [8 1 8 1]
 [1 0 4 7]]
[0 8 6 9]
[[ 0  0  0  0]
 [ 8 -7  2 -8]
 [ 1 -8 -2 -2]]


In [17]:
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)

print(df.iloc[0])

print(df - df.iloc[0])

print(df.iloc[0, ::2])

print(df - df.iloc[0, ::2])

   a  b  c  d
0  0  8  6  9
1  8  1  8  1
2  1  0  4  7
a    0
b    8
c    6
d    9
Name: 0, dtype: int64
   a  b  c  d
0  0  0  0  0
1  8 -7  2 -8
2  1 -8 -2 -2
a    0
c    6
Name: 0, dtype: int64
     a   b    c   d
0  0.0 NaN  0.0 NaN
1  8.0 NaN  2.0 NaN
2  1.0 NaN -2.0 NaN


In [23]:
# NaN -- Not a Number
# NA-значения: NaN, null

# Pandas. Два способа хранения отстутсвующих значений
# 1. индикаторы NaN, None
# 2. null

# None -- объект (накладные расходы). Не работает с sum, min

val1 = np.array([1, 2, 3])
print(val1.sum())

# val1 = np.array([1, None, 2, 3])
# print(val1.sum())

val1 = np.array([1, np.nan, 2, 3])
print(val1)
print(val1.sum())
print(np.sum(val1))
print(np.nansum(val1))

6
[ 1. nan  2.  3.]
nan
nan
6.0


In [26]:
x = pd.Series(range(10), dtype = int)
print(x)

x[0] = None
x[1] = np.nan

print(x)

x1 = pd.Series(['a', 'b', 'c'])
print(x1)

x1[0] = None
x1[1] = np.nan

print(x1)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64
0    a
1    b
2    c
dtype: object
0    None
1     NaN
2       c
dtype: object


In [32]:
#

x2 = pd.Series([1, 2, 3, np.nan, None, pd.NA])
print(x2)

x3 = pd.Series([1, 2, 3, np.nan, None, pd.NA], dtype = 'Int32')
print(x3)

print(x3.isnull())
print(x3[x3.isnull()])
print(x3[x3.notnull()])

print(x3.dropna())

0       1
1       2
2       3
3     NaN
4    None
5    <NA>
dtype: object
0       1
1       2
2       3
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    1
1    2
2    3
dtype: Int32
0    1
1    2
2    3
dtype: Int32


In [35]:
df = pd.DataFrame(
    [
        [1, 2, 3, np.nan, None, pd.NA],
        [1, 2, 3, 4, 5, 6],
        [1, np.nan, 3, 4, np.nan, 6]
    ]
)

print(df)
print(df.dropna())
print(df.dropna(axis=0))
print(df.dropna(axis=1))

   0    1  2    3    4     5
0  1  2.0  3  NaN  NaN  <NA>
1  1  2.0  3  4.0  5.0     6
2  1  NaN  3  4.0  NaN     6
   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6
   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6
   0  2
0  1  3
1  1  3
2  1  3


In [42]:
# how
# - all -- все значения NA
# - any -- хотя бы одно значение
# - thresh = x, остаётся, если присутствует МИНИМУМ х НЕПУСТЫХ значений

df = pd.DataFrame(
    [
        [1, 2, 3, np.nan, None, pd.NA],
        [1, 2, 3, None, 5, 6],
        [1, np.nan, 3, None, np.nan, 6]
    ]
)

print(df)
print(df.dropna(axis=1, how = 'all'))
print(df.dropna(axis=1, how = 'any'))
print(df.dropna(axis=1, thresh = 2))

   0    1  2   3    4     5
0  1  2.0  3 NaN  NaN  <NA>
1  1  2.0  3 NaN  5.0     6
2  1  NaN  3 NaN  NaN     6
   0    1  2    4     5
0  1  2.0  3  NaN  <NA>
1  1  2.0  3  5.0     6
2  1  NaN  3  NaN     6
   0  2
0  1  3
1  1  3
2  1  3
   0    1  2     5
0  1  2.0  3  <NA>
1  1  2.0  3     6
2  1  NaN  3     6
